<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hello.proto

namespace GPBMetadata\Proto;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa6010a1170726f746f2f68656c6c6f2e70726f746f120568656c6c6f22" .
            "1c0a0c48656c6c6f52657175657374120c0a046e616d6518012001280922" .
            "200a0d48656c6c6f526573706f6e7365120f0a076d657373616765180120" .
            "01280932420a074772656574657212370a0853617948656c6c6f12132e68" .
            "656c6c6f2e48656c6c6f526571756573741a142e68656c6c6f2e48656c6c" .
            "6f526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

